services:
  postgres-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_USER: salt
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orderdb
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres-data:
    driver: local   # Local volume to persist data
