steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
            'europe-west1-docker.pkg.dev/microservice-lab-434611/pgp-microservice/order', '-f', './order/Dockerfile', './order']
    env:
    - "DB_USERNAME=${_DB_USERNAME}"
    - "DB_PASSWORD=${_DB_PASSWORD}"
    - "DB_URL=${_DB_URL}"

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'europe-west1-docker.pkg.dev/microservice-lab-434611/pgp-microservice/order']


  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'order-microservice', '--image', 'europe-west1-docker.pkg.dev/microservice-lab-434611/pgp-microservice/order', '--region', 'europe-west1']


images:
  - europe-west1-docker.pkg.dev/microservice-lab-434611/pgp-microservice/order


options:
  logging: CLOUD_LOGGING_ONLY


