api:
  base-path: /api
  controllers:
    orders: /order
    transactions: /transaction
server:
  port: 8080
spring:
  config:
    import: secrets.yml
  application:
    name: inventory
  datasource:
    username: ${database.username}
    password: ${database.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    gcp:
      sql:
        instance-connection-name: ${database.instance-connection-name}
        database-name: ${database.name}
      credentials:
        location: ${database.gcp-auth-location}

