api:
  base-path: /api
  controllers:
    orders: /order
    transactions: /transaction

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: order
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


this:
  base-uri: https://order-983583191360.europe-west1.run.app

inventory:
  base-uri: https://inventory-983583191360.europe-west1.run.app
  endpoints:
    update-inventory-quantity: /api/inventory/update/quantity