api:
  base-path: /api
  controllers:
    orders: /order
    transactions: /transaction

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
    import: sm://projects/983583191360/secrets/supabase-config-inventory
  application:
    name: inventory
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true