server:
  port: 5000
spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5434/orderdb
    username: salt
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop  #create-drop, create, validate etc
    show-sql: true  #Set to true to enable SQL logging