server:
    port: 5000
spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: inventory
    datasource:
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop  #create-drop, create, validate etc
        show-sql: true  #Set to true to enable SQL logging
    cloud:
        gcp:
            sql:
                instance-connection-name: "${INSTANCE_CONNECTION_NAME}"
                database-name: ${DATABASE_NAME}
            credentials:
                location: ${GCP_AUTH_LOCATION}