server:
    port: 5000
spring:
    application:
        name: inventory
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
    data:
        jpa:
            repositories:
                bootstrap-mode: default
